<!DOCTYPE html><html><head><meta charset=UTF-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name="yandex-verification" content="c24e3a17ff2548cc" /><title>АВТОМЕХАНИК</title><link rel="shortcut icon" href="img/domen_ico.ico"><link rel=stylesheet href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css integrity=sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u crossorigin=anonymous><link rel=stylesheet href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css integrity=sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp crossorigin=anonymous><link rel=stylesheet href=css/style.css media="screen"><link rel=stylesheet media=screen,projection href="assets/scrollbut/css/ui.totop.css/"><link rel=stylesheet href=assets/font-awesome/css/font-awesome.min.css><link href="http://fonts.googleapis.com/css?family=Monoton" rel=stylesheet type=text/css><body><div id=fon></div><nav role=navigation class="hidden-xs navbar navbar-fixed-top" id=top_nav><div class=container><div class=row><div class=col-md-12><ul class="top_navigation list-inline col-md-6"><li><a href=html><i>Техпомощь</i></a></li><li><a href=#types><i>Диагностика</i></a></li><li><a href=#info_automobile><i>Автоэлектрик</i></a></li></ul><div class="col-md-3 glavn_desktop_ts"><h1>Самара/Самарская обл.</h1></div><div class="col-md-3 glavn_desktop_phone" href=""><h3>+<span>7</span><span>(908)</span><span>3</span><span>6</span><span>8</span>- <span>0</span><span>3</span>- <span>3</span><span>9</span></h3></div></div></div></div></nav><nav class=visible-xs><div class=container><ul class="nav nav-pills"><li class=dropdown><a class=dropdown-toggle data-toggle=dropdown href=# role=button aria-haspopup=true aria-expanded=false>Меню <i class="fa fa-bars" aria-hidden=true></i></a><ul class=dropdown-menu><li><a href=#main>Техпомощь</a></li><li><a href=#types>Диагностика</a></li><li><a href=#info_automobile>Автоэлектрик</a></li></ul></li></ul><div class="but_baground col-xs-6 col-xs-offset3"></div></div></nav><section id=main><div class=fon2></div><div class=container><div class="row col-md-12"><div class="col-sm-offset-3 col-sm-1 main_info_logo"><img src=img/logo66.png alt=""></div><div class="col-md-4 main_info"><img src=img/Domen244-min.png alt=""></div></div><div class=row><div class="col-md-offset-1 col-md-10 glavn_desktop_help"><h2><span>К</span>РУ<span>Г</span>ЛО<span>С</span>УТ<span>О</span>ЧНА<span>Я</span> ТЕХПО<span>М</span>ОЩЬ НА ДОР<span>О</span>ГАХ</h2></div></div><div class=row><div class="col-md-offset-1 col-md-10"><div class="col-md-4 glavn_desktop_zayvka"><h4>ОСТАВЬТЕ ЗАЯВКУ И МЫ ПЕРЕЗВОНИМ В ТЕЧЕНИИ МИНУТЫ!</h4>
<form method=post action="send.php"><div class=first_name_phone type=text name=first_name_phone><input type="text" required placeholder="Ваше имя" name=first_name_phone id=first_name_phone value=""></div><div class=last_name_phone type=text name=last_name_phone><input type="text" required placeholder="Ваш телефон" name=last_name_phone id=last_name_phone value=""></div><div class=phone_buttons><b data-toggle=modal id=get_contacts name="send"><button  href=#get_contacts_modal_send >Заказать звонок!</button ></b></div>

</form></div>
<div class="col-md-offset-1 col-md-7 glavn_desktop_infocall"><h4><i>ВЫЕЗД ПО ГОРОДУ - 1000р. ЗВОНИТЕ!</i></h4></div><div class="col-md-offset-1 col-md-7 glavn_desktop_infocall"><h3>Выезд:диагноста,автомеханика.<br>Eсть возможность приехать к нам на ТО и другие виды работ:механика,электрика</h3></div></div></div></div></section><section id=a_light><div class=container><div class=row><div class=col-md-12><div class=desktop_a_light><h2>УСЛУГА "ПРИКУРИТЬ АВТО" - 500р.</h2></div></div><div class=col-md-12><div class=desktop_a_light_number><h2>+7 (908) 368-03-39</h2></div></div></div></div></section><section id=types><div class=fon2></div><div class=container><div class=row><div class=col-md-12><div class="col-md-offset-2 col-md-4"><div class=desktop_text_auto><h2><i>Встали на дороге?</i></h2></div></div><div class=col-md-5><div class=desktop_text_auto><h2><i>Не завелись на стоянке?</i></h2></div></div></div></div><div class=row><div class="col-md-offset-3 col-md-7"><div class=desktop_text_autocall><h1>ЗВОНИТЕ, ОТРЕМОНТИРУЕМ!</h1></div></div></div><div class=row><div class="col-md-offset-1 col-md-10 desktop_text_roadcity"><div class=glavn_desktop_help><h2>В<span>Ы</span>ЕЗД<span>Н</span>А<span>Я</span> ДИА<span>Г</span>НОСТИК<span>А</span> ЛЮБ<span>Ы</span>Х АВТОМ<span>О</span>БИЛЕЙ</h2></div></div></div><div class=row><div class=col-md-12><div class=col-md-4><div class=section_info_more><h3>Прикурить,запустить двигатель<br>Буксировка на троссу<br>Снятие секреток с колес автомобиля<br>Вскрытие замков,дверей,капота <br> Замена колеса,запаски</h3></div></div><div class=col-md-4><div class=text_cena><h4>УЗНАТЬ СТОИМОСТЬ РАБОТ ПРЯМО СЕЙЧАС</h4>
<form action=send.php method=post><div class=first_name_phonetext><input type=first_name_phonetext required placeholder="Ваше имя" name=first_name_phone id=first_name_phonetext value=""></div><div class=last_name_phonetext><input type=text required placeholder="Ваш телефон" name=last_name_phone id=last_name_phonetext value=""></div><div class=broken_name_phone><input type=text required placeholder="Наименование поломки(необязательно)" name=broken_name_phone id=broken_name_phone value=""></div><div class=phone_buttons_call><b href="" data-toggle=modal id=get_contacts><button>Заказать звонок!</button></b></div></form></div></div><div class=col-md-4><div class=text_phone_info><h3>РЕМОНТ ДВС,КПП,ХОДОВОЙ <br>Замена: ГРМ,сцепления,прокладки ГБЦ,сальников,подшипников<br>ЗАМЕНА СВЕЧЕЙ - 300р<br>ЦЕНЫ НА ДРУГИЕ УСЛУГИ УТОЧНЯЙТЕ!<br></h3></div></div></div></div></div></section><section id=error><div class=container><div class=row><div class="error_text col-md-12 text-centr"><h2>Зарядка/замена аккумулятора с выездом</h2></div></div></div></section><section id=info_automobile><div class=fon2></div><div class=container><div class=row><div class="col-md-8 col-md-offset-2 text_info_automobile"><h1><span>АВТО</span>ЭЛЕКТРИК</h1><h1>ИСПРАВИТ ЛЮБ<span>УЮ</span> ПОЛО<span>М</span>КУ НА М<span>Е</span>СТЕ!</h1></div></div><div class=row><div class=col-md-12><div class="col-md-5 col-md-offset-1 text_info_jobs"><h4>Замена стартера,генератора,бензонасоса</h4><h4>Ремонт проводки автомобиля</h4><h4>Поиск утечек тока</h4><h4>Проверка узлов предохранителей и реле</h4><h4>Не работает электроника?</h4></div><div class="col-md-5 col-md-offset-1 text_info_jobs_call"><h3><i>Звоните!</i></h3><h3>Автоэлектрик приедет к вам и</h3><h3>исправит всё на месте!</h3></div></div></div><div class=row><div class="col-md-12 text_info_jobs_service"><h2><i>Вызвать нас выгоднее, чем тащить автомобиль в сервис!</i></h2></div></div></div></section><section id=order_call><div class=container><div class=row><div class=col-md-12><div class="col-md-offset-8 col-md-2 call_buttons_specialist_footer"><b href=#get_contacts_modal data-toggle=modal id=get_contacts><button>ЗАКАЗАТЬ ЗВОНОК</button></b></div><div class="col-md-offset-4 col-md-4 copyright"><h5>Copyright © AutoService Design 2016. All Rights Reserved<br><br>Paul Syatkin Development<br>pavel@syatkin.ru</h5></div></div></div></div></section>

<div class="modal fade" id=get_contacts_modal id=get_contacts_modal_send tabindex=-1 role=dialog aria-labelledby=myModalLabel>
<div class="modal-dialog modal-sm" role=document>
<div class=modal-header>
<button type=button class=close data-dismiss=modal aria-label=Close>
<span aria-hidden=true>&times;</span>
</button><h4 class=modal-title id=myModalLabel>Отправить заявку</h4>
</div>
<div class=modal-body>
<form action=send.php method=post>
<div class="col-md-offset-0 first_name_modal">
<input type=first_name_modal required placeholder="Ваше имя" name=first_name_phone id=first_name_modal></div>
<div class="col-md-offset-0 last_name_modal">
<input type=last_name_modal required placeholder="Ваш телефон" name=last_name_phone id=last_name_modal></div
><div class=text-center>
<div class=call_buttons_modal>
<b href="" data-toggle=modal id=get_contacts><button>ОТПРАВИТЬ</button></b></div></div></form></div></div></div>



<script src=assets/jquery/jquery-3.1.0.js></script><script src=js/main.js></script><script src=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js integrity=sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa crossorigin=anonymous></script><script src=assets/scrollbut/js/easing.js type=text/javascript></script><script src=assets/scrollbut/js/jquery.ui.totop.js type=text/javascript></script>
 